//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comunicacion
    {
        public int idcomunicacion { get; set; }
        public string nombrecomunicacion { get; set; }
        public Nullable<int> idtipocomunicacion { get; set; }

        public virtual tipodecomunicacion tipodecomunicacion { get; set; }
        
        public string nombre;
        //public comunicacion()
        //{
        //    tipodecomunicacion = new tipodecomunicacion();
        //}
    }
}
