//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallecompra
    {
        public int iddetallecompra { get; set; }
        public Nullable<decimal> unidades { get; set; }
        public Nullable<decimal> costounidad { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> idproducto { get; set; }
        public Nullable<int> idcompra { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual producto producto { get; set; }
    }
}
