//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrupoNetEntities1 : DbContext
    {
        public GrupoNetEntities1()
            : base("name=GrupoNetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargoes { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<compra> compras { get; set; }
        public virtual DbSet<comunicacion> comunicacions { get; set; }
        public virtual DbSet<detallecompra> detallecompras { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<empresa> empresas { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
        public virtual DbSet<sede> sedes { get; set; }
        public virtual DbSet<subcategoria> subcategorias { get; set; }
        public virtual DbSet<tipodecomunicacion> tipodecomunicacions { get; set; }
        public virtual DbSet<tipodocumento> tipodocumentoes { get; set; }
        public virtual DbSet<tipousuario> tipousuarios { get; set; }
        public virtual DbSet<unidaddemedida> unidaddemedidas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
