//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detallecompras = new HashSet<detallecompra>();
        }
    
        public int idproducto { get; set; }
        public string nombreproducto { get; set; }
        public Nullable<decimal> precioorigen { get; set; }
        public Nullable<decimal> precioventa { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> idsubcategoria { get; set; }
        public Nullable<int> idmarca { get; set; }
        public Nullable<int> idunidadmedida { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecompra> detallecompras { get; set; }
        public virtual marca marca { get; set; }
        public virtual subcategoria subcategoria { get; set; }
        public virtual unidaddemedida unidaddemedida { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
