//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int idventa { get; set; }
        public Nullable<System.DateTime> fechaventa { get; set; }
        public Nullable<decimal> costoventa { get; set; }
        public Nullable<int> idusuraio { get; set; }
        public Nullable<int> idsede { get; set; }
    
        public virtual sede sede { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
